services:
  percona:
    image: percona:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    ports:
      - "3406:3306"
    volumes:
      - percona_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  percona_data:
  postgresql_data: